# Generated by Django 4.1.7 on 2023-03-16 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nums',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_numbers', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('images', models.ImageField(upload_to='images')),
                ('editted_images', models.ImageField(blank=True, null=True, upload_to='filters')),
                ('is_editted', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
